### ISSUE TITLE
Remove resigned people

### ISSUE THREAD

**Issue by MauroMonteneri** [claranet-it/it-portfolio-manager-backend#21]
Find a way to remove resigned people from skills and effort list.
Now the only way is to manually remove entries from the DB.
Some ideas:

- integrate with clockify dashboard (check asToBeExported in sailors list)
-  check if slack account has been deactivatet
- check if Claranet account has been deactivated
- do it manually in a dedicated interface

**Comment by francesco-strazzullo** [comment]
Perhaps a cron job with a slack integration could be the best way to do that
